CREATE TABLE USERS (
  ID                 VARCHAR2(36)   NOT NULL,
  PHONE              VARCHAR2(20),
  EMAIL              VARCHAR2(255),
  PASSWORD_HASH      VARCHAR2(255)  NOT NULL,
  DISPLAY_NAME       VARCHAR2(120)  NOT NULL,
  LOCALE             VARCHAR2(10)   DEFAULT 'en'     NOT NULL,
  PHONE_VERIFIED_AT  TIMESTAMP WITH TIME ZONE,
  EMAIL_VERIFIED_AT  TIMESTAMP WITH TIME ZONE,
  FAILED_ATTEMPTS    NUMBER(3)      DEFAULT 0        NOT NULL,
  LOCKED_UNTIL       TIMESTAMP WITH TIME ZONE,
  STATUS             VARCHAR2(20)   DEFAULT 'ACTIVE' NOT NULL,
  CREATED_AT         TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT         TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_USERS PRIMARY KEY (ID),
  CONSTRAINT CK_USERS_STATUS CHECK (STATUS IN ('ACTIVE','SUSPENDED','DELETED')),
  CONSTRAINT CK_USERS_CONTACT CHECK (PHONE IS NOT NULL OR EMAIL IS NOT NULL)
)
;
CREATE UNIQUE INDEX UX_USERS_PHONE ON USERS(PHONE)
;
CREATE UNIQUE INDEX UX_USERS_EMAIL ON USERS(LOWER(EMAIL))
;
CREATE TABLE DEVICES (
  ID            VARCHAR2(36)  NOT NULL,
  USER_ID       VARCHAR2(36)  NOT NULL,
  PLATFORM      VARCHAR2(10)  NOT NULL,
  MODEL         VARCHAR2(120),
  APP_VERSION   VARCHAR2(20),
  PUSH_TOKEN    VARCHAR2(255),
  LAST_SEEN_AT  TIMESTAMP WITH TIME ZONE,
  CREATED_AT    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_DEVICES PRIMARY KEY (ID),
  CONSTRAINT FK_DEVICES_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
  CONSTRAINT CK_DEVICES_PLATFORM CHECK (PLATFORM IN ('ANDROID','IOS','WEB'))
)
;
CREATE INDEX IX_DEVICES_USER ON DEVICES(USER_ID)
;
CREATE TABLE REFRESH_TOKENS (
  ID           VARCHAR2(36)  NOT NULL,
  USER_ID      VARCHAR2(36)  NOT NULL,
  DEVICE_ID    VARCHAR2(36)  NOT NULL,
  FAMILY_ID    VARCHAR2(36)  NOT NULL,
  TOKEN_HASH   VARCHAR2(128) NOT NULL,
  EXPIRES_AT   TIMESTAMP WITH TIME ZONE NOT NULL,
  REVOKED_AT   TIMESTAMP WITH TIME ZONE,
  REPLACED_BY  VARCHAR2(36),
  CREATED_AT   TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_REFRESH_TOKENS PRIMARY KEY (ID),
  CONSTRAINT FK_RT_USER   FOREIGN KEY (USER_ID)   REFERENCES USERS(ID),
  CONSTRAINT FK_RT_DEVICE FOREIGN KEY (DEVICE_ID) REFERENCES DEVICES(ID)
)
;
CREATE UNIQUE INDEX UX_RT_HASH ON REFRESH_TOKENS(TOKEN_HASH)
;
CREATE INDEX IX_RT_FAMILY ON REFRESH_TOKENS(FAMILY_ID)
