CREATE TABLE MOSQUES (
  ID                 VARCHAR2(36)   NOT NULL,
  NAME               VARCHAR2(200)  NOT NULL,
  TIMEZONE           VARCHAR2(50)   NOT NULL,
  LATITUDE           NUMBER(9,6)    NOT NULL,
  LONGITUDE          NUMBER(9,6)    NOT NULL,
  STATUS             VARCHAR2(20)   DEFAULT 'PROVISIONING' NOT NULL,
  CREATED_AT         TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT         TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_MOSQUES PRIMARY KEY (ID),
  CONSTRAINT CK_MOSQUES_STATUS CHECK (STATUS IN
    ('PROVISIONING','ACTIVE','SUSPENDED','PENDING_DELETION','PURGED'))
)
;
CREATE TABLE MEMBERSHIPS (
  ID          VARCHAR2(36)  NOT NULL,
  MOSQUE_ID   VARCHAR2(36)  NOT NULL,
  USER_ID     VARCHAR2(36)  NOT NULL,
  ROLE        VARCHAR2(20)  NOT NULL,
  STATUS      VARCHAR2(20)  DEFAULT 'ACTIVE' NOT NULL,
  CREATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_MEMBERSHIPS PRIMARY KEY (ID),
  CONSTRAINT FK_MEMBERSHIPS_MOSQUE FOREIGN KEY (MOSQUE_ID) REFERENCES MOSQUES(ID),
  CONSTRAINT FK_MEMBERSHIPS_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
  CONSTRAINT CK_MEMBERSHIPS_ROLE CHECK (ROLE IN
    ('ADMIN','TREASURER','COMMITTEE','STAFF','MEMBER')),
  CONSTRAINT CK_MEMBERSHIPS_STATUS CHECK (STATUS IN ('ACTIVE','SUSPENDED','REMOVED')),
  CONSTRAINT UX_MEMBERSHIPS_MOSQUE_USER UNIQUE (MOSQUE_ID, USER_ID)
)
;
CREATE INDEX IX_MEMBERSHIPS_USER ON MEMBERSHIPS(USER_ID)
;
