CREATE TABLE FUNDS (
  ID              VARCHAR2(36)   NOT NULL,
  TENANT_ID       VARCHAR2(36)   NOT NULL,
  TYPE            VARCHAR2(20)   NOT NULL,
  NAME            VARCHAR2(100)  NOT NULL,
  ZAKAT_ELIGIBLE  NUMBER(1)      DEFAULT 0 NOT NULL,
  CREATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_FUNDS PRIMARY KEY (ID),
  CONSTRAINT FK_FUNDS_MOSQUE FOREIGN KEY (TENANT_ID) REFERENCES MOSQUES(ID),
  CONSTRAINT CK_FUNDS_TYPE CHECK (TYPE IN
    ('GENERAL','ZAKAT','SADAQAH','LILLAH','FITRANA','QURBANI','WAQF','BUILDING','CUSTOM')),
  CONSTRAINT CK_FUNDS_ZAKAT_ELIGIBLE CHECK (ZAKAT_ELIGIBLE IN (0,1))
)
;
CREATE INDEX IX_FUNDS_TENANT ON FUNDS(TENANT_ID)
;
