CREATE TABLE INVITATIONS (
  ID              VARCHAR2(36)   NOT NULL,
  MOSQUE_ID       VARCHAR2(36)   NOT NULL,
  EMAIL_OR_PHONE  VARCHAR2(255)  NOT NULL,
  ROLE            VARCHAR2(20)   NOT NULL,
  TOKEN_HASH      VARCHAR2(128)  NOT NULL,
  INVITED_BY      VARCHAR2(36)   NOT NULL,
  EXPIRES_AT      TIMESTAMP WITH TIME ZONE NOT NULL,
  ACCEPTED_AT     TIMESTAMP WITH TIME ZONE,
  CREATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_INVITATIONS PRIMARY KEY (ID),
  CONSTRAINT FK_INVITATIONS_MOSQUE FOREIGN KEY (MOSQUE_ID) REFERENCES MOSQUES(ID),
  CONSTRAINT FK_INVITATIONS_INVITER FOREIGN KEY (INVITED_BY) REFERENCES USERS(ID),
  CONSTRAINT CK_INVITATIONS_ROLE CHECK (ROLE IN
    ('ADMIN','TREASURER','COMMITTEE','STAFF','MEMBER'))
)
;
CREATE UNIQUE INDEX UX_INVITATIONS_HASH ON INVITATIONS(TOKEN_HASH)
;
CREATE INDEX IX_INVITATIONS_MOSQUE ON INVITATIONS(MOSQUE_ID)
;
