CREATE TABLE PRAYER_CONFIG (
  TENANT_ID            VARCHAR2(36)  NOT NULL,
  CALCULATION_METHOD   VARCHAR2(30)  NOT NULL,
  FAJR_OFFSET_MIN       NUMBER(4)    DEFAULT 0 NOT NULL,
  DHUHR_OFFSET_MIN      NUMBER(4)    DEFAULT 0 NOT NULL,
  ASR_OFFSET_MIN        NUMBER(4)    DEFAULT 0 NOT NULL,
  MAGHRIB_OFFSET_MIN    NUMBER(4)    DEFAULT 0 NOT NULL,
  ISHA_OFFSET_MIN       NUMBER(4)    DEFAULT 0 NOT NULL,
  FAJR_FIXED_TIME       VARCHAR2(5),
  DHUHR_FIXED_TIME      VARCHAR2(5),
  ASR_FIXED_TIME        VARCHAR2(5),
  MAGHRIB_FIXED_TIME    VARCHAR2(5),
  ISHA_FIXED_TIME       VARCHAR2(5),
  JUMUAH_TIME           VARCHAR2(5),
  UPDATED_AT            TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_PRAYER_CONFIG PRIMARY KEY (TENANT_ID),
  CONSTRAINT FK_PRAYER_CONFIG_MOSQUE FOREIGN KEY (TENANT_ID) REFERENCES MOSQUES(ID)
)
;
