CREATE TABLE HOUSEHOLDS (
  ID                  VARCHAR2(36)   NOT NULL,
  TENANT_ID           VARCHAR2(36)   NOT NULL,
  NAME                VARCHAR2(200)  NOT NULL,
  HEAD_INDIVIDUAL_ID  VARCHAR2(36),
  ADDRESS_LINE1       VARCHAR2(200),
  AREA                VARCHAR2(100),
  PHONE               VARCHAR2(20),
  MONTHLY_DUES_MINOR  NUMBER(18)     DEFAULT 0 NOT NULL,
  COLLECTOR_USER_ID   VARCHAR2(36),
  EXEMPT              NUMBER(1)      DEFAULT 0 NOT NULL,
  JOINED_ON           DATE,
  STATUS              VARCHAR2(20)   DEFAULT 'ACTIVE' NOT NULL,
  CREATED_BY          VARCHAR2(36)   NOT NULL,
  CREATED_AT          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_HOUSEHOLDS PRIMARY KEY (ID),
  CONSTRAINT FK_HH_TENANT FOREIGN KEY (TENANT_ID) REFERENCES MOSQUES(ID),
  CONSTRAINT FK_HH_COLLECTOR FOREIGN KEY (COLLECTOR_USER_ID) REFERENCES USERS(ID),
  CONSTRAINT FK_HH_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USERS(ID),
  CONSTRAINT CK_HH_STATUS CHECK (STATUS IN ('ACTIVE','INACTIVE','MOVED')),
  CONSTRAINT CK_HH_DUES CHECK (MONTHLY_DUES_MINOR >= 0),
  CONSTRAINT CK_HH_EXEMPT CHECK (EXEMPT IN (0,1))
)
;
CREATE INDEX IX_HH_TENANT ON HOUSEHOLDS(TENANT_ID, STATUS)
;
CREATE TABLE INDIVIDUALS (
  ID             VARCHAR2(36)   NOT NULL,
  TENANT_ID      VARCHAR2(36)   NOT NULL,
  HOUSEHOLD_ID   VARCHAR2(36)   NOT NULL,
  USER_ID        VARCHAR2(36),
  FULL_NAME      VARCHAR2(200)  NOT NULL,
  RELATION       VARCHAR2(20)   NOT NULL,
  PHONE          VARCHAR2(20),
  DATE_OF_BIRTH  DATE,
  GENDER         VARCHAR2(10),
  CREATED_BY     VARCHAR2(36)   NOT NULL,
  CREATED_AT     TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_INDIVIDUALS PRIMARY KEY (ID),
  CONSTRAINT FK_IND_TENANT FOREIGN KEY (TENANT_ID) REFERENCES MOSQUES(ID),
  CONSTRAINT FK_IND_HH FOREIGN KEY (HOUSEHOLD_ID) REFERENCES HOUSEHOLDS(ID),
  CONSTRAINT FK_IND_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
  CONSTRAINT FK_IND_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USERS(ID),
  CONSTRAINT CK_IND_RELATION CHECK (RELATION IN
    ('HEAD','SPOUSE','CHILD','PARENT','SIBLING','OTHER'))
)
;
CREATE INDEX IX_IND_TENANT_HH ON INDIVIDUALS(TENANT_ID, HOUSEHOLD_ID)
;
-- HOUSEHOLDS.HEAD_INDIVIDUAL_ID and INDIVIDUALS.HOUSEHOLD_ID reference each other —
-- this FK is added after INDIVIDUALS exists rather than inline on HOUSEHOLDS.
ALTER TABLE HOUSEHOLDS ADD CONSTRAINT FK_HH_HEAD
  FOREIGN KEY (HEAD_INDIVIDUAL_ID) REFERENCES INDIVIDUALS(ID)
;
CREATE TABLE DONATIONS (
  ID                 VARCHAR2(36)   NOT NULL,
  TENANT_ID          VARCHAR2(36)   NOT NULL,
  FUND_ID            VARCHAR2(36)   NOT NULL,
  AMOUNT_MINOR       NUMBER(18)     NOT NULL,
  CURRENCY           VARCHAR2(3)    NOT NULL,
  OCCURRED_ON        DATE           NOT NULL,
  METHOD             VARCHAR2(20)   NOT NULL,
  DONOR_HOUSEHOLD_ID VARCHAR2(36),
  DONOR_NAME         VARCHAR2(200),
  ANONYMOUS          NUMBER(1)      DEFAULT 0 NOT NULL,
  RECEIPT_NO         VARCHAR2(30),
  NOTE               VARCHAR2(500),
  ADJUSTS_ID         VARCHAR2(36),
  ADJUSTMENT_REASON  VARCHAR2(500),
  CREATED_BY         VARCHAR2(36)   NOT NULL,
  CREATED_AT         TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_DONATIONS PRIMARY KEY (ID),
  CONSTRAINT FK_DON_TENANT FOREIGN KEY (TENANT_ID) REFERENCES MOSQUES(ID),
  CONSTRAINT FK_DON_FUND FOREIGN KEY (FUND_ID) REFERENCES FUNDS(ID),
  CONSTRAINT FK_DON_HH FOREIGN KEY (DONOR_HOUSEHOLD_ID) REFERENCES HOUSEHOLDS(ID),
  CONSTRAINT FK_DON_ADJUSTS FOREIGN KEY (ADJUSTS_ID) REFERENCES DONATIONS(ID),
  CONSTRAINT FK_DON_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USERS(ID),
  CONSTRAINT UX_DON_RECEIPT UNIQUE (TENANT_ID, RECEIPT_NO),
  CONSTRAINT CK_DON_AMOUNT CHECK (AMOUNT_MINOR <> 0),
  CONSTRAINT CK_DON_ANONYMOUS CHECK (ANONYMOUS IN (0,1)),
  CONSTRAINT CK_DON_METHOD CHECK (METHOD IN
    ('CASH','BANK','MOBILE_MONEY','CARD','CHEQUE','IN_KIND'))
)
;
CREATE INDEX IX_DON_TENANT_DATE ON DONATIONS(TENANT_ID, OCCURRED_ON DESC)
;
CREATE INDEX IX_DON_TENANT_FUND ON DONATIONS(TENANT_ID, FUND_ID, OCCURRED_ON)
;
CREATE INDEX IX_DON_TENANT_HH ON DONATIONS(TENANT_ID, DONOR_HOUSEHOLD_ID, OCCURRED_ON)
;
-- Append-only per FR-DON-4: no UPDATE ever, corrections are a new row via ADJUSTS_ID.
CREATE OR REPLACE TRIGGER TRG_DONATIONS_IMMUTABLE
BEFORE UPDATE ON DONATIONS
FOR EACH ROW
BEGIN
  RAISE_APPLICATION_ERROR(-20001, 'DONATIONS is append-only — record an adjustment instead of updating.');
END;
/
BEGIN
  DBMS_RLS.ADD_POLICY(
    object_schema   => 'MASJID',
    object_name     => 'HOUSEHOLDS',
    policy_name     => 'HOUSEHOLDS_TENANT_POLICY',
    function_schema => 'MASJID',
    policy_function => 'TENANT_PREDICATE',
    statement_types => 'SELECT,INSERT,UPDATE,DELETE',
    update_check    => TRUE
  );
  DBMS_RLS.ADD_POLICY(
    object_schema   => 'MASJID',
    object_name     => 'INDIVIDUALS',
    policy_name     => 'INDIVIDUALS_TENANT_POLICY',
    function_schema => 'MASJID',
    policy_function => 'TENANT_PREDICATE',
    statement_types => 'SELECT,INSERT,UPDATE,DELETE',
    update_check    => TRUE
  );
  DBMS_RLS.ADD_POLICY(
    object_schema   => 'MASJID',
    object_name     => 'DONATIONS',
    policy_name     => 'DONATIONS_TENANT_POLICY',
    function_schema => 'MASJID',
    policy_function => 'TENANT_PREDICATE',
    statement_types => 'SELECT,INSERT,UPDATE,DELETE',
    update_check    => TRUE
  );
END;
/
