CREATE TABLE EXPENSE_CATEGORIES (
  ID              VARCHAR2(36)   NOT NULL,
  TENANT_ID       VARCHAR2(36)   NOT NULL,
  NAME            VARCHAR2(100)  NOT NULL,
  ZAKAT_ELIGIBLE  NUMBER(1)      DEFAULT 0 NOT NULL,
  ASNAF_CATEGORY  VARCHAR2(30),
  IS_SYSTEM       NUMBER(1)      DEFAULT 0 NOT NULL,
  CREATED_BY      VARCHAR2(36)   NOT NULL,
  CREATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_EXPCAT PRIMARY KEY (ID),
  CONSTRAINT FK_EXPCAT_TENANT FOREIGN KEY (TENANT_ID) REFERENCES MOSQUES(ID),
  CONSTRAINT FK_EXPCAT_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USERS(ID),
  CONSTRAINT UX_EXPCAT_NAME UNIQUE (TENANT_ID, NAME),
  CONSTRAINT CK_EXPCAT_ZAKAT_ELIGIBLE CHECK (ZAKAT_ELIGIBLE IN (0,1)),
  CONSTRAINT CK_EXPCAT_ASNAF CHECK (ASNAF_CATEGORY IS NULL OR ASNAF_CATEGORY IN
    ('FUQARA','MASAKIN','AMILIN','MUALLAFAT','RIQAB','GHARIMIN','FI_SABILILLAH','IBN_SABIL'))
)
;
CREATE TABLE EXPENSES (
  ID                 VARCHAR2(36)   NOT NULL,
  TENANT_ID          VARCHAR2(36)   NOT NULL,
  FUND_ID            VARCHAR2(36)   NOT NULL,
  CATEGORY_ID        VARCHAR2(36)   NOT NULL,
  AMOUNT_MINOR       NUMBER(18)     NOT NULL,
  CURRENCY           VARCHAR2(3)    NOT NULL,
  OCCURRED_ON        DATE           NOT NULL,
  PAYEE              VARCHAR2(200),
  DESCRIPTION        VARCHAR2(500),
  METHOD             VARCHAR2(20)   NOT NULL,
  APPROVAL_STATUS    VARCHAR2(20)   DEFAULT 'POSTED' NOT NULL,
  ADJUSTS_ID         VARCHAR2(36),
  ADJUSTMENT_REASON  VARCHAR2(500),
  CREATED_BY         VARCHAR2(36)   NOT NULL,
  CREATED_AT         TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_EXPENSES PRIMARY KEY (ID),
  CONSTRAINT FK_EXP_TENANT FOREIGN KEY (TENANT_ID) REFERENCES MOSQUES(ID),
  CONSTRAINT FK_EXP_FUND FOREIGN KEY (FUND_ID) REFERENCES FUNDS(ID),
  CONSTRAINT FK_EXP_CAT FOREIGN KEY (CATEGORY_ID) REFERENCES EXPENSE_CATEGORIES(ID),
  CONSTRAINT FK_EXP_ADJUSTS FOREIGN KEY (ADJUSTS_ID) REFERENCES EXPENSES(ID),
  CONSTRAINT FK_EXP_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USERS(ID),
  CONSTRAINT CK_EXP_AMOUNT CHECK (AMOUNT_MINOR <> 0),
  CONSTRAINT CK_EXP_APPROVAL CHECK (APPROVAL_STATUS IN ('DRAFT','PENDING','POSTED','REJECTED')),
  CONSTRAINT CK_EXP_METHOD CHECK (METHOD IN
    ('CASH','BANK','MOBILE_MONEY','CARD','CHEQUE','IN_KIND'))
)
;
CREATE INDEX IX_EXP_TENANT_DATE ON EXPENSES(TENANT_ID, OCCURRED_ON DESC)
;
CREATE INDEX IX_EXP_TENANT_FUND ON EXPENSES(TENANT_ID, FUND_ID, OCCURRED_ON)
;
-- Append-only, same discipline as DONATIONS (FR-DON-4's equivalent for expenses).
CREATE OR REPLACE TRIGGER TRG_EXPENSES_IMMUTABLE
BEFORE UPDATE ON EXPENSES
FOR EACH ROW
BEGIN
  RAISE_APPLICATION_ERROR(-20002, 'EXPENSES is append-only — record an adjustment instead of updating.');
END;
/
BEGIN
  DBMS_RLS.ADD_POLICY(
    object_schema   => 'MASJID',
    object_name     => 'EXPENSE_CATEGORIES',
    policy_name     => 'EXPCAT_TENANT_POLICY',
    function_schema => 'MASJID',
    policy_function => 'TENANT_PREDICATE',
    statement_types => 'SELECT,INSERT,UPDATE,DELETE',
    update_check    => TRUE
  );
  DBMS_RLS.ADD_POLICY(
    object_schema   => 'MASJID',
    object_name     => 'EXPENSES',
    policy_name     => 'EXPENSES_TENANT_POLICY',
    function_schema => 'MASJID',
    policy_function => 'TENANT_PREDICATE',
    statement_types => 'SELECT,INSERT,UPDATE,DELETE',
    update_check    => TRUE
  );
END;
/
