CREATE TABLE DUES_CHARGES (
  ID             VARCHAR2(36)   NOT NULL,
  TENANT_ID      VARCHAR2(36)   NOT NULL,
  HOUSEHOLD_ID   VARCHAR2(36)   NOT NULL,
  PERIOD         VARCHAR2(7)    NOT NULL,
  AMOUNT_MINOR   NUMBER(18)     NOT NULL,
  PAID_MINOR     NUMBER(18)     DEFAULT 0 NOT NULL,
  CURRENCY       VARCHAR2(3)    NOT NULL,
  DUE_ON         DATE           NOT NULL,
  STATUS         VARCHAR2(20)   DEFAULT 'PENDING' NOT NULL,
  WAIVED_BY      VARCHAR2(36),
  WAIVED_REASON  VARCHAR2(500),
  CREATED_BY     VARCHAR2(36)   NOT NULL,
  CREATED_AT     TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_DUES_CHARGES PRIMARY KEY (ID),
  CONSTRAINT FK_DC_TENANT FOREIGN KEY (TENANT_ID) REFERENCES MOSQUES(ID),
  CONSTRAINT FK_DC_HH FOREIGN KEY (HOUSEHOLD_ID) REFERENCES HOUSEHOLDS(ID),
  CONSTRAINT FK_DC_WAIVED_BY FOREIGN KEY (WAIVED_BY) REFERENCES USERS(ID),
  CONSTRAINT FK_DC_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USERS(ID),
  CONSTRAINT UX_DC_PERIOD UNIQUE (TENANT_ID, HOUSEHOLD_ID, PERIOD),
  CONSTRAINT CK_DC_STATUS CHECK (STATUS IN ('PENDING','PARTIAL','PAID','WAIVED'))
)
;
CREATE INDEX IX_DC_TENANT_PERIOD ON DUES_CHARGES(TENANT_ID, PERIOD, STATUS)
;
-- No separate (TENANT_ID, HOUSEHOLD_ID, PERIOD) index: UX_DC_PERIOD's unique constraint
-- already creates one on that exact column list (ORA-01408 on a duplicate).
CREATE TABLE DUES_PAYMENTS (
  ID             VARCHAR2(36)   NOT NULL,
  TENANT_ID      VARCHAR2(36)   NOT NULL,
  CHARGE_ID      VARCHAR2(36)   NOT NULL,
  FUND_ID        VARCHAR2(36)   NOT NULL,
  AMOUNT_MINOR   NUMBER(18)     NOT NULL,
  CURRENCY       VARCHAR2(3)    NOT NULL,
  PAID_ON        DATE           NOT NULL,
  METHOD         VARCHAR2(20)   NOT NULL,
  COLLECTED_BY   VARCHAR2(36),
  CREATED_BY     VARCHAR2(36)   NOT NULL,
  CREATED_AT     TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_DUES_PAYMENTS PRIMARY KEY (ID),
  CONSTRAINT FK_DP_TENANT FOREIGN KEY (TENANT_ID) REFERENCES MOSQUES(ID),
  CONSTRAINT FK_DP_CHARGE FOREIGN KEY (CHARGE_ID) REFERENCES DUES_CHARGES(ID),
  CONSTRAINT FK_DP_FUND FOREIGN KEY (FUND_ID) REFERENCES FUNDS(ID),
  CONSTRAINT FK_DP_COLLECTED_BY FOREIGN KEY (COLLECTED_BY) REFERENCES USERS(ID),
  CONSTRAINT FK_DP_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USERS(ID),
  CONSTRAINT CK_DP_AMOUNT CHECK (AMOUNT_MINOR > 0)
)
;
CREATE INDEX IX_DP_TENANT_CHARGE ON DUES_PAYMENTS(TENANT_ID, CHARGE_ID)
;
-- Payments are append-only, same discipline as DONATIONS/EXPENSES — a charge's
-- PAID_MINOR/STATUS are recomputed from the payment log, never edited directly, and a
-- mis-recorded payment is corrected by recording a new payment for the difference
-- (there is no adjustment-entry column here since dues isn't in the sync engine's
-- proven-entity scope yet and doesn't need ADJUSTS_ID linkage for that).
CREATE OR REPLACE TRIGGER TRG_DUES_PAYMENTS_IMMUTABLE
BEFORE UPDATE ON DUES_PAYMENTS
FOR EACH ROW
BEGIN
  RAISE_APPLICATION_ERROR(-20003, 'DUES_PAYMENTS is append-only.');
END;
/
BEGIN
  DBMS_RLS.ADD_POLICY(
    object_schema   => 'MASJID',
    object_name     => 'DUES_CHARGES',
    policy_name     => 'DUES_CHARGES_TENANT_POLICY',
    function_schema => 'MASJID',
    policy_function => 'TENANT_PREDICATE',
    statement_types => 'SELECT,INSERT,UPDATE,DELETE',
    update_check    => TRUE
  );
  DBMS_RLS.ADD_POLICY(
    object_schema   => 'MASJID',
    object_name     => 'DUES_PAYMENTS',
    policy_name     => 'DUES_PAYMENTS_TENANT_POLICY',
    function_schema => 'MASJID',
    policy_function => 'TENANT_PREDICATE',
    statement_types => 'SELECT,INSERT,UPDATE,DELETE',
    update_check    => TRUE
  );
END;
/
