CREATE TABLE STAFF (
  ID                  VARCHAR2(36)   NOT NULL,
  TENANT_ID           VARCHAR2(36)   NOT NULL,
  NAME                VARCHAR2(200)  NOT NULL,
  ROLE_TITLE          VARCHAR2(100),
  PHONE               VARCHAR2(20),
  MONTHLY_SALARY_MINOR NUMBER(18)    DEFAULT 0 NOT NULL,
  CURRENCY            VARCHAR2(3)    DEFAULT 'BDT' NOT NULL,
  STATUS              VARCHAR2(20)   DEFAULT 'ACTIVE' NOT NULL,
  JOINED_ON           DATE,
  CREATED_BY          VARCHAR2(36)   NOT NULL,
  CREATED_AT          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_STAFF PRIMARY KEY (ID),
  CONSTRAINT FK_STAFF_TENANT FOREIGN KEY (TENANT_ID) REFERENCES MOSQUES(ID),
  CONSTRAINT FK_STAFF_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USERS(ID),
  CONSTRAINT CK_STAFF_STATUS CHECK (STATUS IN ('ACTIVE','INACTIVE'))
)
;
CREATE INDEX IX_STAFF_TENANT_STATUS ON STAFF(TENANT_ID, STATUS)
;
CREATE TABLE PAYROLL_RUNS (
  ID          VARCHAR2(36)   NOT NULL,
  TENANT_ID   VARCHAR2(36)   NOT NULL,
  PERIOD      VARCHAR2(7)    NOT NULL,
  FUND_ID     VARCHAR2(36)   NOT NULL,
  STATUS      VARCHAR2(20)   DEFAULT 'DRAFT' NOT NULL,
  POSTED_AT   TIMESTAMP WITH TIME ZONE,
  CREATED_BY  VARCHAR2(36)   NOT NULL,
  CREATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_PAYROLL_RUNS PRIMARY KEY (ID),
  CONSTRAINT FK_PR_TENANT FOREIGN KEY (TENANT_ID) REFERENCES MOSQUES(ID),
  CONSTRAINT FK_PR_FUND FOREIGN KEY (FUND_ID) REFERENCES FUNDS(ID),
  CONSTRAINT FK_PR_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USERS(ID),
  CONSTRAINT UX_PR_PERIOD UNIQUE (TENANT_ID, PERIOD),
  CONSTRAINT CK_PR_STATUS CHECK (STATUS IN ('DRAFT','POSTED'))
)
;
CREATE TABLE PAYROLL_LINES (
  ID            VARCHAR2(36)   NOT NULL,
  TENANT_ID     VARCHAR2(36)   NOT NULL,
  RUN_ID        VARCHAR2(36)   NOT NULL,
  STAFF_ID      VARCHAR2(36)   NOT NULL,
  AMOUNT_MINOR  NUMBER(18)     NOT NULL,
  CURRENCY      VARCHAR2(3)    NOT NULL,
  EXPENSE_ID    VARCHAR2(36),
  CREATED_AT    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_PAYROLL_LINES PRIMARY KEY (ID),
  CONSTRAINT FK_PL_TENANT FOREIGN KEY (TENANT_ID) REFERENCES MOSQUES(ID),
  CONSTRAINT FK_PL_RUN FOREIGN KEY (RUN_ID) REFERENCES PAYROLL_RUNS(ID),
  CONSTRAINT FK_PL_STAFF FOREIGN KEY (STAFF_ID) REFERENCES STAFF(ID),
  CONSTRAINT FK_PL_EXPENSE FOREIGN KEY (EXPENSE_ID) REFERENCES EXPENSES(ID),
  CONSTRAINT UX_PL_RUN_STAFF UNIQUE (TENANT_ID, RUN_ID, STAFF_ID)
)
;
CREATE INDEX IX_PL_TENANT_RUN ON PAYROLL_LINES(TENANT_ID, RUN_ID)
;
BEGIN
  DBMS_RLS.ADD_POLICY(
    object_schema   => 'MASJID',
    object_name     => 'STAFF',
    policy_name     => 'STAFF_TENANT_POLICY',
    function_schema => 'MASJID',
    policy_function => 'TENANT_PREDICATE',
    statement_types => 'SELECT,INSERT,UPDATE,DELETE',
    update_check    => TRUE
  );
  DBMS_RLS.ADD_POLICY(
    object_schema   => 'MASJID',
    object_name     => 'PAYROLL_RUNS',
    policy_name     => 'PAYROLL_RUNS_TENANT_POLICY',
    function_schema => 'MASJID',
    policy_function => 'TENANT_PREDICATE',
    statement_types => 'SELECT,INSERT,UPDATE,DELETE',
    update_check    => TRUE
  );
  DBMS_RLS.ADD_POLICY(
    object_schema   => 'MASJID',
    object_name     => 'PAYROLL_LINES',
    policy_name     => 'PAYROLL_LINES_TENANT_POLICY',
    function_schema => 'MASJID',
    policy_function => 'TENANT_PREDICATE',
    statement_types => 'SELECT,INSERT,UPDATE,DELETE',
    update_check    => TRUE
  );
END;
/
