CREATE TABLE COMMITTEE_MEMBERS (
  ID          VARCHAR2(36)   NOT NULL,
  TENANT_ID   VARCHAR2(36)   NOT NULL,
  NAME        VARCHAR2(200)  NOT NULL,
  POSITION    VARCHAR2(100),
  PHONE       VARCHAR2(20),
  TERM_START  DATE,
  TERM_END    DATE,
  STATUS      VARCHAR2(20)   DEFAULT 'ACTIVE' NOT NULL,
  CREATED_BY  VARCHAR2(36)   NOT NULL,
  CREATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_COMMITTEE_MEMBERS PRIMARY KEY (ID),
  CONSTRAINT FK_CM_TENANT FOREIGN KEY (TENANT_ID) REFERENCES MOSQUES(ID),
  CONSTRAINT FK_CM_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USERS(ID),
  CONSTRAINT CK_CM_STATUS CHECK (STATUS IN ('ACTIVE','INACTIVE'))
)
;
CREATE INDEX IX_CM_TENANT_STATUS ON COMMITTEE_MEMBERS(TENANT_ID, STATUS)
;
BEGIN
  DBMS_RLS.ADD_POLICY(
    object_schema   => 'MASJID',
    object_name     => 'COMMITTEE_MEMBERS',
    policy_name     => 'COMMITTEE_MEMBERS_TENANT_POLICY',
    function_schema => 'MASJID',
    policy_function => 'TENANT_PREDICATE',
    statement_types => 'SELECT,INSERT,UPDATE,DELETE',
    update_check    => TRUE
  );
END;
/
