CREATE TABLE EVENTS (
  ID           VARCHAR2(36)   NOT NULL,
  TENANT_ID    VARCHAR2(36)   NOT NULL,
  TITLE        VARCHAR2(200)  NOT NULL,
  DESCRIPTION  VARCHAR2(2000),
  STARTS_AT    TIMESTAMP WITH TIME ZONE NOT NULL,
  ENDS_AT      TIMESTAMP WITH TIME ZONE,
  LOCATION     VARCHAR2(200),
  CREATED_BY   VARCHAR2(36)   NOT NULL,
  CREATED_AT   TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_EVENTS PRIMARY KEY (ID),
  CONSTRAINT FK_EV_TENANT FOREIGN KEY (TENANT_ID) REFERENCES MOSQUES(ID),
  CONSTRAINT FK_EV_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USERS(ID)
)
;
CREATE INDEX IX_EVENTS_TENANT_STARTS ON EVENTS(TENANT_ID, STARTS_AT)
;
BEGIN
  DBMS_RLS.ADD_POLICY(
    object_schema   => 'MASJID',
    object_name     => 'EVENTS',
    policy_name     => 'EVENTS_TENANT_POLICY',
    function_schema => 'MASJID',
    policy_function => 'TENANT_PREDICATE',
    statement_types => 'SELECT,INSERT,UPDATE,DELETE',
    update_check    => TRUE
  );
END;
/
