CREATE TABLE ANNOUNCEMENTS (
  ID          VARCHAR2(36)   NOT NULL,
  TENANT_ID   VARCHAR2(36)   NOT NULL,
  TITLE       VARCHAR2(200)  NOT NULL,
  BODY        VARCHAR2(2000) NOT NULL,
  URGENT      NUMBER(1)      DEFAULT 0 NOT NULL,
  CREATED_BY  VARCHAR2(36)   NOT NULL,
  CREATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_ANNOUNCEMENTS PRIMARY KEY (ID),
  CONSTRAINT FK_AN_TENANT FOREIGN KEY (TENANT_ID) REFERENCES MOSQUES(ID),
  CONSTRAINT FK_AN_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USERS(ID),
  CONSTRAINT CK_AN_URGENT CHECK (URGENT IN (0,1))
)
;
CREATE INDEX IX_AN_TENANT_CREATED ON ANNOUNCEMENTS(TENANT_ID, CREATED_AT)
;
BEGIN
  DBMS_RLS.ADD_POLICY(
    object_schema   => 'MASJID',
    object_name     => 'ANNOUNCEMENTS',
    policy_name     => 'ANNOUNCEMENTS_TENANT_POLICY',
    function_schema => 'MASJID',
    policy_function => 'TENANT_PREDICATE',
    statement_types => 'SELECT,INSERT,UPDATE,DELETE',
    update_check    => TRUE
  );
END;
/
