CREATE TABLE PLANS (
  CODE          VARCHAR2(20)  NOT NULL,
  NAME          VARCHAR2(60)  NOT NULL,
  ENTITLEMENTS  CLOB          NOT NULL,
  ACTIVE        NUMBER(1)     DEFAULT 1 NOT NULL,
  CONSTRAINT PK_PLANS PRIMARY KEY (CODE),
  CONSTRAINT CK_PLANS_JSON CHECK (ENTITLEMENTS IS JSON),
  CONSTRAINT CK_PLANS_ACTIVE CHECK (ACTIVE IN (0,1))
)
;
CREATE TABLE SUBSCRIPTIONS (
  ID                   VARCHAR2(36) NOT NULL,
  MOSQUE_ID            VARCHAR2(36) NOT NULL,
  PLAN_CODE            VARCHAR2(20) NOT NULL,
  STATUS               VARCHAR2(20) NOT NULL,
  BILLING_PERIOD       VARCHAR2(10) DEFAULT 'MONTHLY' NOT NULL,
  PRICE_MINOR          NUMBER(18)   DEFAULT 0 NOT NULL,
  CURRENCY             VARCHAR2(3)  DEFAULT 'BDT' NOT NULL,
  CURRENT_PERIOD_START TIMESTAMP WITH TIME ZONE,
  CURRENT_PERIOD_END   TIMESTAMP WITH TIME ZONE,
  TRIAL_ENDS_AT        TIMESTAMP WITH TIME ZONE,
  CANCEL_AT_PERIOD_END NUMBER(1)    DEFAULT 0 NOT NULL,
  PROVIDER             VARCHAR2(30),
  PROVIDER_REF         VARCHAR2(120),
  CREATED_AT           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_SUBSCRIPTIONS PRIMARY KEY (ID),
  CONSTRAINT UX_SUB_MOSQUE UNIQUE (MOSQUE_ID),
  CONSTRAINT FK_SUB_MOSQUE FOREIGN KEY (MOSQUE_ID) REFERENCES MOSQUES(ID),
  CONSTRAINT FK_SUB_PLAN FOREIGN KEY (PLAN_CODE) REFERENCES PLANS(CODE),
  CONSTRAINT CK_SUB_STATUS CHECK (STATUS IN ('TRIALING','ACTIVE','PAST_DUE','CANCELED','EXPIRED')),
  CONSTRAINT CK_SUB_CANCEL CHECK (CANCEL_AT_PERIOD_END IN (0,1))
)
;
-- Global tables (no TENANT_ID — see multi-tenancy doc's global-table list), so no VPD
-- policy: a subscription's own MOSQUE_ID FK + UX_SUB_MOSQUE is the only scoping that
-- makes sense for a "the platform bills the mosque" record, mirroring MOSQUES/MEMBERSHIPS.
INSERT INTO PLANS (CODE, NAME, ENTITLEMENTS) VALUES (
  'BASIC', 'Basic',
  '{"features":[],"limits":{"adminUsers":3,"members":null,"historyMonths":12}}'
)
;
INSERT INTO PLANS (CODE, NAME, ENTITLEMENTS) VALUES (
  'PRO', 'Pro',
  '{"features":["ONLINE_DONATIONS","PAYROLL","EXPORT"],"limits":{"adminUsers":10,"members":null,"historyMonths":36}}'
)
;
