-- Global (no TENANT_ID) — a preference belongs to the user, not a mosque, same
-- category as USERS/DEVICES. Urgent/janazah announcements are not a toggle here by
-- design (jobs-and-notifications doc §5: URGENT bypasses quiet hours and is
-- deliberately not user-suppressible — a funeral notice is a religious obligation, not
-- a subscribable category).
CREATE TABLE NOTIFICATION_PREFERENCES (
  USER_ID           VARCHAR2(36) NOT NULL,
  ANNOUNCEMENTS     NUMBER(1)    DEFAULT 1 NOT NULL,
  DUES_REMINDERS    NUMBER(1)    DEFAULT 1 NOT NULL,
  PRAYER_REMINDERS  NUMBER(1)    DEFAULT 1 NOT NULL,
  EVENTS            NUMBER(1)    DEFAULT 1 NOT NULL,
  QUIET_HOURS_START VARCHAR2(5)  DEFAULT '22:00' NOT NULL,
  QUIET_HOURS_END   VARCHAR2(5)  DEFAULT '06:00' NOT NULL,
  UPDATED_AT        TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_NOTIFICATION_PREFS PRIMARY KEY (USER_ID),
  CONSTRAINT FK_NP_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
  CONSTRAINT CK_NP_ANNOUNCEMENTS CHECK (ANNOUNCEMENTS IN (0,1)),
  CONSTRAINT CK_NP_DUES CHECK (DUES_REMINDERS IN (0,1)),
  CONSTRAINT CK_NP_PRAYER CHECK (PRAYER_REMINDERS IN (0,1)),
  CONSTRAINT CK_NP_EVENTS CHECK (EVENTS IN (0,1))
)
;
